# Questo workflow permette di eseguire l'agente chatbot direttamente dall'interfaccia UI di GitHub.
name: Avvia Agente Chatbot

# Questo trigger permette di avviare il workflow manualmente dalla tab "Actions".
on:
  workflow_dispatch:
    # Definisce i campi di input che verranno mostrati nell'interfaccia di GitHub.
    inputs:
      user_query:
        description: 'La tua richiesta per la user story'
        required: true
        default: 'Voglio una user story per il login con autenticazione a due fattori'

jobs:
  run-chatbot:
    # Specifica che il lavoro deve essere eseguito su una macchina virtuale Ubuntu fornita da GitHub.
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Scarica il codice del repository sulla macchina virtuale.
      - name: Check-out repository
        uses: actions/checkout@v4

      # Passo 2: Imposta l'ambiente Python.
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Installa tutte le dipendenze dal file requirements.txt.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Esegue lo script del chatbot in modalità non interattiva.
      # Utilizza il modello di Azure e passa la query dell'utente dall'input dell'interfaccia di GitHub.
      - name: Esegui Chatbot con Azure OpenAI
        env:
          # Carica le credenziali e gli endpoint dai "secrets" del repository GitHub per sicurezza.
          AZURE_SEARCH_ENDPOINT: ${{ secrets.AZURE_SEARCH_ENDPOINT }}
          AZURE_SEARCH_API_KEY: ${{ secrets.AZURE_SEARCH_API_KEY }}
          AZURE_SEARCH_INDEX_NAME: ${{ secrets.AZURE_SEARCH_INDEX_NAME }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        run: python chatbot.py --model azure --query "${{ github.event.inputs.user_query }}"