# This workflow allows you to run the chatbot agent directly from the GitHub UI.
name: Avvia Agente Chatbot

# This trigger allows the workflow to be run manually from the Actions tab.
on:
  workflow_dispatch:
    # Define the input fields that will be shown in the GitHub UI.
    inputs:
      user_query:
        description: 'La tua richiesta per la user story'
        required: true
        default: 'Voglio una user story per il login con autenticazione a due fattori'

jobs:
  run-chatbot:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check-out the repository code.
      - name: Check-out repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment.
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install all dependencies from requirements.txt.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the chatbot in non-interactive mode.
      # It uses the Azure model and passes the user's query from the GitHub UI input.
      - name: Esegui Chatbot con Azure OpenAI
        env:
          AZURE_SEARCH_ENDPOINT: ${{ secrets.AZURE_SEARCH_ENDPOINT }}
          AZURE_SEARCH_API_KEY: ${{ secrets.AZURE_SEARCH_API_KEY }}
          AZURE_SEARCH_INDEX_NAME: ${{ secrets.AZURE_SEARCH_INDEX_NAME }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        run: python chatbot.py --model azure --query "${{ github.event.inputs.user_query }}"
