# Questo è il nome del workflow di GitHub Actions.
# Verrà visualizzato nella tab "Actions" del tuo repository GitHub.
name: Valutazione CI del Modello RAG

# Questa sezione definisce il trigger per il workflow.
# 'on: push:' significa che il workflow si avvierà ogni volta che fai un push del codice.
# 'branches: [ main ]' specifica che dovrebbe avviarsi solo per i push sul branch 'main'.
on:
  push:
    branches: [ main ]

# Un workflow è composto da uno o più lavori che possono essere eseguiti in sequenza o in parallelo.
jobs:
  # Questo lavoro si chiama 'evaluate'. Puoi nominarlo come preferisci.
  evaluate:
    # Il tipo di macchina virtuale su cui eseguire il lavoro. 'ubuntu-latest' è una scelta standard e affidabile.
    runs-on: ubuntu-latest

    # 'steps' rappresenta una sequenza di task che verranno eseguiti come parte del lavoro.
    steps:
      # Passo 1: Scarica il codice del tuo repository.
      # Questa azione permette al workflow di accedere a tutti i file del tuo progetto.
      - name: Check-out repository
        uses: actions/checkout@v4

      # Passo 2: Imposta l'ambiente Python.
      # Specifica quale versione di Python utilizzare.
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Installa tutte le dipendenze necessarie.
      # Questo comando legge il tuo file requirements.txt e installa tutte le librerie.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Esegue lo script di valutazione RAG.
      # Questo è il passo centrale del workflow. Esegue il tuo script di valutazione principale.
      # Il blocco 'env' è cruciale per la sicurezza: mappa i "Secrets" di GitHub a
      # variabili d'ambiente a cui lo script può accedere in modo sicuro.
      - name: Run RAG evaluation
        env:
          AZURE_SEARCH_ENDPOINT: ${{ secrets.AZURE_SEARCH_ENDPOINT }}
          AZURE_SEARCH_API_KEY: ${{ secrets.AZURE_SEARCH_API_KEY }}
          AZURE_SEARCH_INDEX_NAME: ${{ secrets.AZURE_SEARCH_INDEX_NAME }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        run: python 03_valuta_modello.py